import { Metadata } from "next";

export const siteConfig = {
  name: "LexusTracker",
  description:
    "Advanced RDW Data - Comprehensive insights into Lexus IS250C vehicles in the Netherlands using RDW official data",
  url: "https://lexustracker.nl",
  ogImage: "https://lexustracker.nl/og-image.jpg",
  keywords: [
    "Lexus tracker",
    "Lexus IS250C",
    "car tracking Netherlands",
    "vehicle insights RDW",
    "Lexus IS250C statistics",
    "Dutch vehicle registration",
    "Lexus convertible tracking",
    "RDW open data",
    "Lexus volgen",
    "Lexus IS250C tracker",
    "auto volgen Nederland",
    "voertuig inzichten RDW",
    "Lexus IS250C statistieken",
    "Nederlandse voertuigregistratie",
    "Lexus cabrio volgen",
    "RDW open gegevens",
    "Lexus tracker Nederland",
    "auto tracker Nederland",
    "voertuig tracker",
    "automotive analytics",
    "car statistics dashboard",
    "vehicle monitoring platform",
    "Lexus car history",
    "Dutch car database",
    "vehicle registration lookup",
    "car insurance status",
    "Lexus IS 250C Netherlands",
    "automotive insights platform",
    "vehicle data visualization",
    "car data analysis",
    "vehicle market trends",
    "automotive statistics",
    "automotive analytics",
    "auto statistieken dashboard",
    "voertuig monitoring platform",
    "Lexus auto geschiedenis",
    "Nederlandse auto database",
    "voertuigregistratie opzoeken",
    "auto verzekering status",
    "Lexus IS 250C Nederland",
    "voertuig inzichten platform",
    "voertuiggegevens visualisatie",
    "auto data analyse",
    "voertuig markt trends",
    "automotive statistieken",
    "auto gegevens Nederland",
    "voertuig database Nederland",
    "kenteken informatie",
    "auto informatie opzoeken",
    "Lexus IS250C registration data Netherlands",
    "track Lexus convertible statistics",
    "RDW vehicle information dashboard",
    "Dutch automotive data platform",
    "Lexus IS250C market analysis",
    "vehicle tracking web application",
    "automotive statistics Netherlands",
    "car data analytics platform",
    "Lexus registration trends",
    "vehicle monitoring dashboard",
    "Netherlands car registration lookup",
    "Dutch vehicle database search",
    "automotive data insights Netherlands",
    "Lexus IS250C registratiegegevens Nederland",
    "Lexus cabrio statistieken volgen",
    "RDW voertuiginformatie dashboard",
    "Nederlandse automotive data platform",
    "Lexus IS250C marktanalyse",
    "voertuigvolging webapplicatie",
    "automotive statistieken Nederland",
    "auto data analytics platform",
    "Lexus registratie trends",
    "voertuig monitoring dashboard",
    "kenteken opzoeken",
    "RDW gegevens",
    "voertuiggegevens",
    "auto informatie",
    "verzekeringsstatus",
    "APK vervaldatum",
    "voertuig specificaties",
    "automobile Nederland",
    "Nederland voertuigregistratie opzoeken",
    "Nederlandse voertuig database zoeken",
    "automotive data inzichten Nederland",
    "auto statistieken platform",
    "voertuig tracking systeem",
    "RDW data platform",
    "kenteken check Nederland",
    "auto geschiedenis opzoeken",
    "voertuig status controleren",
    "Nederlandse auto gegevens",
    "Lexus IS250C Nederland database",
    "cabrio registratie Nederland",
    "auto registratie trends",
    "voertuiggegevens platform",
    "RDW statistieken",
    "Nederlandse automotive analytics",
  ],
  authors: [
    {
      name: "LexusTracker Team",
      url: "https://lexustracker.nl",
    },
  ],
  creator: "LexusTracker",
  publisher: "LexusTracker",
  category: "Automotive Technology",
  classification: "Vehicle Tracking Platform",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  themeColor: "#000000",
  colorScheme: "dark light",
};

export function constructMetadata({
  title = siteConfig.name,
  description = siteConfig.description,
  image = siteConfig.ogImage,
  noIndex = false,
  keywords,
  canonical,
  ...props
}: {
  title?: string;
  description?: string;
  image?: string;
  noIndex?: boolean;
  keywords?: string[];
  canonical?: string;
} & Metadata = {}): Metadata {
  const combinedKeywords = keywords
    ? [...siteConfig.keywords, ...keywords]
    : siteConfig.keywords;

  return {
    title: {
      default: title,
      template: `%s | ${siteConfig.name}`,
    },
    description,
    keywords: combinedKeywords,
    authors: siteConfig.authors,
    creator: siteConfig.creator,
    publisher: siteConfig.publisher,
    category: siteConfig.category,
    classification: siteConfig.classification,
    formatDetection: siteConfig.formatDetection,
    metadataBase: new URL(siteConfig.url),
    openGraph: {
      type: "website",
      locale: "en_US",
      url: canonical || siteConfig.url,
      title,
      description,
      siteName: siteConfig.name,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: title,
          type: "image/jpeg",
        },
        {
          url: image.replace(".jpg", "-square.jpg"),
          width: 600,
          height: 600,
          alt: title,
          type: "image/jpeg",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
      creator: "@lexustracker",
      site: "@lexustracker",
    },
    facebook: {
      appId: "your-facebook-app-id", // Replace with actual app ID
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      nocache: false,
      googleBot: {
        index: !noIndex,
        follow: !noIndex,
        noimageindex: false,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    verification: {
      google: "your-google-site-verification", // Replace with actual verification code
      yandex: "your-yandex-verification", // Replace with actual verification code
      other: {
        "msvalidate.01": "your-bing-verification", // Replace with actual verification code
      },
    },
    alternates: {
      canonical: canonical || siteConfig.url,
      languages: {
        "en-US": `${siteConfig.url}/en`,
        "nl-NL": `${siteConfig.url}/nl`,
        "x-default": siteConfig.url,
      },
      media: {
        "only screen and (max-width: 600px)": `${siteConfig.url}/mobile`,
      },
      types: {
        "application/rss+xml": `${siteConfig.url}/feed.xml`,
        "application/atom+xml": `${siteConfig.url}/atom.xml`,
      },
    },
    appLinks: {
      web: {
        url: siteConfig.url,
        should_fallback: true,
      },
    },
    archives: [`${siteConfig.url}/archive`],
    assets: [`${siteConfig.url}/assets`],
    bookmarks: [`${siteConfig.url}/bookmarks`],
    other: {
      "apple-mobile-web-app-capable": "yes",
      "apple-mobile-web-app-status-bar-style": "black-translucent",
      "apple-mobile-web-app-title": siteConfig.name,
      "mobile-web-app-capable": "yes",
      "msapplication-TileColor": "#000000",
      "msapplication-config": "/browserconfig.xml",
      "msapplication-TileImage": "/mstile-144x144.png",
      "application-name": siteConfig.name,
      "msapplication-tooltip": siteConfig.description,
      "msapplication-starturl": "/",
      "msapplication-navbutton-color": "#000000",
      "msapplication-window": "width=1024;height=768",
      "msapplication-task": "name=Dashboard;action-uri=/;icon-uri=/favicon.ico",
      "theme-color": siteConfig.themeColor,
      "color-scheme": siteConfig.colorScheme,
      "supported-color-schemes": siteConfig.colorScheme,
      HandheldFriendly: "true",
      MobileOptimized: "320",
      "target-densitydpi": "device-dpi",
      "viewport-fit": "cover",
      web_author: siteConfig.creator,
      "revisit-after": "7 days",
      distribution: "global",
      rating: "general",
      referrer: "origin-when-cross-origin",
      "format-detection": "telephone=no, date=no, address=no, email=no, url=no",
      "mobile-web-app-status-bar-style": "black-translucent",
      "apple-mobile-web-app-orientations": "portrait-any",
      "msvalidate.01": "your-bing-validation-code", // Replace with actual validation code
    },
    ...props,
  };
}

export const defaultMetadata = constructMetadata();
