import { Metadata } from "next";

export const siteConfig = {
  name: "Z3 RADAR",
  description:
    "Advanced RDW Data - Comprehensive insights into BMW Z3 vehicles in the Netherlands using RDW official data",
  url: "https://Z3radar.com",
  ogImage: "https://Z3radar.com/og-image.jpg",
  keywords: [
    "BMW tracker",
    "BMW Z3",
    "car tracking Netherlands",
    "vehicle insights RDW",
    "BMW Z3 statistics",
    "Dutch vehicle registration",
    "BMW convertible tracking",
    "RDW open data",
    "BMW volgen",
    "BMW Z3 tracker",
    "auto volgen Nederland",
    "voertuig inzichten RDW",
    "BMW Z3 statistieken",
    "Nederlandse voertuigregistratie",
    "BMW cabrio volgen",
    "RDW open gegevens",
    "BMW tracker Nederland",
    "auto tracker Nederland",
    "voertuig tracker",
    "automotive analytics",
    "car statistics dashboard",
    "vehicle monitoring platform",
    "BMW car history",
    "Dutch car database",
    "vehicle registration lookup",
    "car insurance status",
    "BMW IS 250C Netherlands",
    "automotive insights platform",
    "vehicle data visualization",
    "car data analysis",
    "vehicle market trends",
    "automotive statistics",
    "automotive analytics",
    "auto statistieken dashboard",
    "voertuig monitoring platform",
    "BMW auto geschiedenis",
    "Nederlandse auto database",
    "voertuigregistratie opzoeken",
    "auto verzekering status",
    "BMW IS 250C Nederland",
    "voertuig inzichten platform",
    "voertuiggegevens visualisatie",
    "auto data analyse",
    "voertuig markt trends",
    "automotive statistieken",
    "auto gegevens Nederland",
    "voertuig database Nederland",
    "kenteken informatie",
    "auto informatie opzoeken",
    "BMW Z3 registration data Netherlands",
    "track BMW convertible statistics",
    "RDW vehicle information dashboard",
    "Dutch automotive data platform",
    "BMW Z3 market analysis",
    "vehicle tracking web application",
    "automotive statistics Netherlands",
    "car data analytics platform",
    "BMW registration trends",
    "vehicle monitoring dashboard",
    "Netherlands car registration lookup",
    "Dutch vehicle database search",
    "automotive data insights Netherlands",
    "BMW Z3 registratiegegevens Nederland",
    "BMW cabrio statistieken volgen",
    "RDW voertuiginformatie dashboard",
    "Nederlandse automotive data platform",
    "BMW Z3 marktanalyse",
    "voertuigvolging webapplicatie",
    "automotive statistieken Nederland",
    "auto data analytics platform",
    "BMW registratie trends",
    "voertuig monitoring dashboard",
    "kenteken opzoeken",
    "RDW gegevens",
    "voertuiggegevens",
    "auto informatie",
    "verzekeringsstatus",
    "APK vervaldatum",
    "voertuig specificaties",
    "automobile Nederland",
    "Nederland voertuigregistratie opzoeken",
    "Nederlandse voertuig database zoeken",
    "automotive data inzichten Nederland",
    "auto statistieken platform",
    "voertuig tracking systeem",
    "RDW data platform",
    "kenteken check Nederland",
    "auto geschiedenis opzoeken",
    "voertuig status controleren",
    "Nederlandse auto gegevens",
    "BMW Z3 Nederland database",
    "cabrio registratie Nederland",
    "auto registratie trends",
    "voertuiggegevens platform",
    "RDW statistieken",
    "Nederlandse automotive analytics",
  ],
  authors: [
    {
      name: "Z3 RADAR Team",
      url: "https://Z3radar.com",
    },
  ],
  creator: "Z3 RADAR",
  publisher: "Z3 RADAR",
  category: "Automotive Technology",
  classification: "Vehicle Tracking Platform",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  themeColor: "#000000",
  colorScheme: "dark light",
};

export function constructMetadata({
  title = siteConfig.name,
  description = siteConfig.description,
  image = siteConfig.ogImage,
  noIndex = false,
  keywords,
  canonical,
  ...props
}: {
  title?: string;
  description?: string;
  image?: string;
  noIndex?: boolean;
  keywords?: string[];
  canonical?: string;
} & Metadata = {}): Metadata {
  const combinedKeywords = keywords
    ? [...siteConfig.keywords, ...keywords]
    : siteConfig.keywords;

  return {
    title: {
      default: title,
      template: `%s | ${siteConfig.name}`,
    },
    description,
    keywords: combinedKeywords,
    authors: siteConfig.authors,
    creator: siteConfig.creator,
    publisher: siteConfig.publisher,
    category: siteConfig.category,
    classification: siteConfig.classification,
    formatDetection: siteConfig.formatDetection,
    metadataBase: new URL(siteConfig.url),
    openGraph: {
      type: "website",
      locale: "en_US",
      url: canonical || siteConfig.url,
      title,
      description,
      siteName: siteConfig.name,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: title,
          type: "image/jpeg",
        },
        {
          url: image.replace(".jpg", "-square.jpg"),
          width: 600,
          height: 600,
          alt: title,
          type: "image/jpeg",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
      creator: "@Z3 RADAR",
      site: "@Z3 RADAR",
    },
    facebook: {
      appId: "your-facebook-app-id", // Replace with actual app ID
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      nocache: false,
      googleBot: {
        index: !noIndex,
        follow: !noIndex,
        noimageindex: false,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    verification: {
      google: "your-google-site-verification", // Replace with actual verification code
      yandex: "your-yandex-verification", // Replace with actual verification code
      other: {
        "msvalidate.01": "your-bing-verification", // Replace with actual verification code
      },
    },
    alternates: {
      canonical: canonical || siteConfig.url,
      languages: {
        "en-US": `${siteConfig.url}/en`,
        "nl-NL": `${siteConfig.url}/nl`,
        "x-default": siteConfig.url,
      },
      media: {
        "only screen and (max-width: 600px)": `${siteConfig.url}/mobile`,
      },
      types: {
        "application/rss+xml": `${siteConfig.url}/feed.xml`,
        "application/atom+xml": `${siteConfig.url}/atom.xml`,
      },
    },
    appLinks: {
      web: {
        url: siteConfig.url,
        should_fallback: true,
      },
    },
    archives: [`${siteConfig.url}/archive`],
    assets: [`${siteConfig.url}/assets`],
    bookmarks: [`${siteConfig.url}/bookmarks`],
    other: {
      "apple-mobile-web-app-capable": "yes",
      "apple-mobile-web-app-status-bar-style": "black-translucent",
      "apple-mobile-web-app-title": siteConfig.name,
      "mobile-web-app-capable": "yes",
      "msapplication-TileColor": "#000000",
      "msapplication-config": "/browserconfig.xml",
      "msapplication-TileImage": "/mstile-144x144.png",
      "application-name": siteConfig.name,
      "msapplication-tooltip": siteConfig.description,
      "msapplication-starturl": "/",
      "msapplication-navbutton-color": "#000000",
      "msapplication-window": "width=1024;height=768",
      "msapplication-task": "name=Dashboard;action-uri=/;icon-uri=/favicon.ico",
      "theme-color": siteConfig.themeColor,
      "color-scheme": siteConfig.colorScheme,
      "supported-color-schemes": siteConfig.colorScheme,
      HandheldFriendly: "true",
      MobileOptimized: "320",
      "target-densitydpi": "device-dpi",
      "viewport-fit": "cover",
      web_author: siteConfig.creator,
      "revisit-after": "7 days",
      distribution: "global",
      rating: "general",
      referrer: "origin-when-cross-origin",
      "format-detection": "telephone=no, date=no, address=no, email=no, url=no",
      "mobile-web-app-status-bar-style": "black-translucent",
      "apple-mobile-web-app-orientations": "portrait-any",
      "msvalidate.01": "your-bing-validation-code", // Replace with actual validation code
    },
    ...props,
  };
}

export const defaultMetadata = constructMetadata();
